# Generated by Django 5.2.4 on 2025-12-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CONTENT_APP', '0003_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
