# Generated by Django 5.2.8 on 2025-12-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CONTENT_APP", "0003_demopage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
